<a href="https://colab.research.google.com/github/jyotigiri7219/Practice/blob/main/MissingData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

**Finding Miaaing Data**

In [7]:
data = {
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,np.nan,np.nan,4,np.nan],
    'C':[1,2,3,np.nan,5],
    'D':[6,7,np.nan,9,10],
    'E':[11,12,13,14,15]
}
df = pd.DataFrame(data)

In [8]:
df

     A    B    C     D   E
0  1.0  NaN  1.0   6.0  11
1  2.0  NaN  2.0   7.0  12
2  NaN  NaN  3.0   NaN  13
3  4.0  4.0  NaN   9.0  14
4  5.0  NaN  5.0  10.0  15

In [10]:
df.isna()

       A      B      C      D      E
0  False   True  False  False  False
1  False   True  False  False  False
2   True   True  False   True  False
3  False  False   True  False  False
4  False   True  False  False  False

In [11]:
df.isna().sum() # row nan value finde

A    1
B    4
C    1
D    1
E    0
dtype: int64

In [12]:
df.isna().any() # column nan value find

A     True
B     True
C     True
D     True
E    False
dtype: bool

In [16]:
df

     A    B    C     D   E
0  1.0  NaN  1.0   6.0  11
1  2.0  NaN  2.0   7.0  12
2  NaN  NaN  3.0   NaN  13
3  4.0  4.0  NaN   9.0  14
4  5.0  NaN  5.0  10.0  15

In [19]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []