<a href="https://colab.research.google.com/github/jyotigiri7219/Practice/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

In [5]:
labels = ['A','B','C']
l = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [6]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

**Series**

In [7]:
pd.Series(data=arr,index=labels)

A    10
B    20
C    30
dtype: int64

**DataFrame**

In [8]:
data = {
    "Name":["Ayush","Jyoti","Adarsh","Roshni"],
    "Age":[8,20,14,17],
    "City":["Virar","Andheri","Mira road","nallsopra"],
    "Saleary":[20000,25000,30000,50000]
}

In [9]:
pd.DataFrame(data)

     Name  Age       City  Saleary
0   Ayush    8      Virar    20000
1   Jyoti   20    Andheri    25000
2  Adarsh   14  Mira road    30000
3  Roshni   17  nallsopra    50000

**Create use data in the list **

In [28]:
data_list = [
    ["Ayush","Jyoti","Adarsh","Roshni"],
    [8,20,14,17],
    ["Virar","Andheri","Mira road","nallsopra"],
    [20000,25000,30000,50000]
    ]
df2 = pd.DataFrame(data_list)

In [32]:
df2 = pd.DataFrame(data_list)
df2

       0        1          2          3
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [33]:
df2

       0        1          2          3
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [34]:
columns = ["Nmae","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)
df2

    Nmae      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000