<a href="https://colab.research.google.com/github/jyotigiri7219/Practice/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['A','B','C']
l = [10,20,30]
arr = np.array([10,20,30])
d = {1:10,2:20,3:30}

In [3]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

**Series**

In [4]:
pd.Series(data=arr,index=labels)

A    10
B    20
C    30
dtype: int64

**DataFrame**

In [5]:
data = {
    "Name":["Ayush","Jyoti","Adarsh","Roshni"],
    "Age":[8,20,14,17],
    "City":["Virar","Andheri","Mira road","nallsopra"],
    "Saleary":[20000,25000,30000,50000]
}

In [6]:
pd.DataFrame(data)

     Name  Age       City  Saleary
0   Ayush    8      Virar    20000
1   Jyoti   20    Andheri    25000
2  Adarsh   14  Mira road    30000
3  Roshni   17  nallsopra    50000

**Create use data in the list **

In [7]:
data_list = [
    ["Ayush","Jyoti","Adarsh","Roshni"],
    [8,20,14,17],
    ["Virar","Andheri","Mira road","nallsopra"],
    [20000,25000,30000,50000]
    ]
df2 = pd.DataFrame(data_list)

In [ ]:
df2 = pd.DataFrame(data_list)
df2

       0        1          2          3
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [8]:
df2

       0        1          2          3
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [9]:
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)
df2

    Name      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [11]:

df2

    Name      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

**select index and columns**

In [12]:
df2

    Name      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [13]:
df2[["Name","City"]]

    Name       City
0  Ayush     Adarsh
1      8         14
2  Virar  Mira road
3  20000      30000

**New column cri**

In [14]:
df2["DPT"] = ["doctor","engineer","doctor","Engineerr"]

In [15]:
df2

    Name      Age       City     Salary        DPT
0  Ayush    Jyoti     Adarsh     Roshni     doctor
1      8       20         14         17   engineer
2  Virar  Andheri  Mira road  nallsopra     doctor
3  20000    25000      30000      50000  Engineerr

**Remove column**

In [16]:
df2.drop("DPT", axis =  1)

    Name      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [17]:
df2

    Name      Age       City     Salary        DPT
0  Ayush    Jyoti     Adarsh     Roshni     doctor
1      8       20         14         17   engineer
2  Virar  Andheri  Mira road  nallsopra     doctor
3  20000    25000      30000      50000  Engineerr

In [33]:
df2.drop("DPT", axis = 1, inplace = True, errors='ignore')
df2

    Name      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [35]:
df2.drop(["Name","City"], axis = 1)

       Age     Salary
0    Jyoti     Roshni
1       20         17
2  Andheri  nallsopra
3    25000      50000

In [36]:
df2

    Name      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

**Selecting rows**

In [37]:
df2

    Name      Age       City     Salary
0  Ayush    Jyoti     Adarsh     Roshni
1      8       20         14         17
2  Virar  Andheri  Mira road  nallsopra
3  20000    25000      30000      50000

In [40]:
df2.loc[0]

Name       Ayush
Age        Jyoti
City      Adarsh
Salary    Roshni
Name: 0, dtype: object

In [41]:
df2.iloc[3]

Name      20000
Age       25000
City      30000
Salary    50000
Name: 3, dtype: object